/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Ultimate Grocery Full App Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Profile": "Profile",
          "Edit": "Edit",
          "Reviews": "Reviews",
          "Change Password": "Change Password",
          "Languages": "Languages",
          "Contact Us": "Contact Us",
          "Faq & Help": "Faq & Help",
          "Privacy And Terms": "Privacy And Terms",
          "About": "About",
          "Logout": "Logout",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Privacy Policy": "Privacy Policy",
          "About Us": "About Us",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Submit": "Submit",
          "Edit Profile": "Edit Profile",
          "Choose From": "Choose From",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "Cancel": "Cancel",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Email": "Email",
          "Mobile No": "Mobile No",
          "Available": "Available",
          "Save Profile": "Save Profile",
          "Connection Failed": "Connection Failed",
          "Could not connect to network,": "Could not connect to network,",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Verify your phone number": "Verify your phone number",
          "Fresh fruits and Vegetables": "Fresh fruits and Vegetables",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health",
          "Grocery to your door steps": "Grocery to your door steps",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.",
          "Best quality grocery": "Best quality grocery",
          "Best quality product with organic maintenance but with affordable price.": "Best quality product with organic maintenance but with affordable price.",
          "Fastest Delivery": "Fastest Delivery",
          "Free delivery service for highest cart value, without minimum payment.": "Free delivery service for highest cart value, without minimum payment.",
          "Skip": "Skip",
          "Previous": "Previous",
          "Get Started": "Get Started",
          "Next": "Next",
          "Welcome": "Welcome",
          "Please login to your acount": "Please login to your account",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "Sign In": "Sign In",
          "Want to delivery partner with us ?": "Want to delivery partner with us ?",
          " Join Now": " Join Now",
          "Phone Number": "Phone Number",
          "Send OTP": "Send OTP",
          "Order": "Order",
          "Choose Status": "Choose Status",
          "Update Status": "Update Status",
          "Order Cancelled by user": "Order Cancelled by user",
          "Order Delivered": "Order Delivered",
          "Order Rejected": "Order Rejected",
          "Orders": "Orders",
          "grams": "grams",
          "kg": "kg",
          "ltr": "ltr",
          "ml": "ml",
          "Order Item Total": "Order Item Total",
          "Order Delivery Charge": "Order Delivery Charge",
          "Split Order Tax": "Split Order Tax",
          "Split Order Discount": "Split Order Discount",
          "Split Order Wallet Discount": "Split Order Wallet Discount",
          "Amount To Collect": "Amount To Collect",
          "Deliver to": "Deliver to",
          "Basic Detail": "Basic Detail",
          "Order ID": "Order ID",
          "Payment Method": "Payment Method",
          "COD": "COD",
          "PAID": "PAID",
          "Delivery On": "Delivery On",
          "Order Tracking": "Order Tracking",
          "User Information": "User Information",
          "Store Information": "Store Information",
          "Current Orders": "Current Orders",
          "Past Orders": "Past Orders",
          "Drivers": "Drivers",
          "ORDER #": "ORDER #",
          "Register Request": "Register Request",
          "Verify Phone": "Verify Phone",
          "Verify E-Mail": "Verify E-Mail",
          "Confirm Password": "Confirm Password",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Status": "Status",
          "Continue": "Continue",
          "Your your cover image": "Your your cover image",
          "Store Address": "Store Address",
          "Choose City": "Choose City",
          "Select City": "Select City",
          "Register Now": "Register Now",
          "Reset Password": "Reset Password",
          "Please enter your credentials": "Please enter your credentials",
          "New Password": "New Password",
          "Update Password": "Update Password",
          "Received from": "Received from",
          "No Internet Connection": "No Internet Connection",
          "Account": "Account",
          "Tracking Order": "Tracking Order",
          "Order Total": "Order Total",
          "Payment Method :": "Payment Method :",
          "Session expired!": "Session expired!",
          "Please wait": "Please wait",
          "All fields are required": "All fields are required",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Your account is blocked, please contact administrator": "Your account is blocked, please contact administrator",
          "Something went wrong while signin": "Something went wrong while signin",
          "Something went wrong": "Something went wrong",
          "Something went wrong while signup": "Something went wrong while signup",
          "Phone Number is required": "Phone Number is required",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Verify": "Verify",
          "Contact": "Contact",
          "Call": "Call",
          "Choose status": "Choose status",
          "Updating Order": "Updating Order",
          "Sending OTP": "Sending OTP",
          "Location services are disabled.": "Location services are disabled.",
          "Location permissions are denied": "Location permissions are denied",
          "Location permissions are permanently denied, we cannot request permissions.": "Location permissions are permanently denied, we cannot request permissions.",
          "Contact Number Verified": "Contact Number Verified",
          "Email Verified": "Email Verified",
          "E-mail is required": "E-mail is required",
          "Password mismatch": "Password mismatch",
          "Your Register Request Sent": "Your Register Request Sent",
          "Password Updated": "Password Updated",
          "Start Location": "Start Location",
          "End Location": "End Location",
          "created": "created",
          "rejected": "rejected",
          "delivered": "delivered",
          "accepted": "accepted",
          "cancelled": "cancelled",
          "ongoing": "ongoing",
        },
        'hi_IN': {
          "Profile": "प्रोफ़ाइल",
          "Edit": "संपादन करना",
          "Reviews": "समीक्षा",
          "Change Password": "पासवर्ड बदलें",
          "Languages": "बोली",
          "Contact Us": "संपर्क करें",
          "Faq & Help": "पूछे जाने वाले प्रश्न और सहायता",
          "Privacy And Terms": "गोपनीयता और शर्तें",
          "About": "के बारे में",
          "Logout": "लॉग आउट",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "Privacy Policy": "गोपनीयता नीति",
          "About Us": "हमारे बारे में",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Submit": "प्रस्तुत करना",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Choose From": "से चुनें",
          "Gallery": "गेलरी",
          "Camera": "कैमरा",
          "Cancel": "रद्द करना",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Email": "ईमेल",
          "Mobile No": "मोबाइल नहीं है",
          "Available": "उपलब्ध",
          "Save Profile": "प्रोफ़ाइल बचा",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network,": "नेटवर्क से कनेक्ट नहीं हो सका,",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें।",
          "retry": "पुन: प्रयास करें",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "Fresh fruits and Vegetables": "ताजे फल और सब्जियां",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "ताजे फल और सब्जियां स्वस्थ आहार का एक महत्वपूर्ण हिस्सा हैं। इनमें आवश्यक विटामिन, खनिज, फाइबर और अन्य पोषक तत्व होते हैं जो अच्छे स्वास्थ्य के लिए आवश्यक हैं",
          "Grocery to your door steps": "आपके दरवाजे तक किराना",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "हम धीरे-धीरे इस बारे में अधिक जागरूक हो रहे हैं कि हमारी व्यक्तिगत पसंद हमारे ग्रह को कैसे प्रभावित कर सकती है। और भोजन - हम इसका उपभोग कैसे करते हैं और हम इसके लिए कैसे खरीदारी करते हैं - यह सबसे महत्वपूर्ण तरीकों में से एक है जिससे हम फर्क कर सकते हैं।",
          "Best quality grocery": "उत्तम गुणवत्ता किराना",
          "Best quality product with organic maintenance but with affordable price.": "जैविक रखरखाव के साथ सर्वोत्तम गुणवत्ता वाला उत्पाद लेकिन सस्ती कीमत के साथ।",
          "Fastest Delivery": "सबसे तेज़ डिलीवरी",
          "Free delivery service for highest cart value, without minimum payment.": "न्यूनतम भुगतान के बिना उच्चतम कार्ट मूल्य के लिए निःशुल्क वितरण सेवा।",
          "Skip": "छोड़ें",
          "Previous": "पिछला",
          "Get Started": "शुरू हो जाओ",
          "Next": "अगला",
          "Welcome": "स्वागत",
          "Please login to your acount": "कृपया अपने खाते लॉग इन करें",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Sign In": "साइन इन करें",
          "Want to delivery partner with us ?": "हमारे साथ डिलीवरी पार्टनर चाहते हैं?",
          " Join Now": "अब सम्मिलित हों",
          "Phone Number": "फ़ोन नंबर",
          "Send OTP": "OTP भेजें",
          "Order": "आदेश",
          "Choose Status": "स्थिति चुनें",
          "Update Status": "नवीनतम स्थिति",
          "Order Cancelled by user": "उपयोगकर्ता द्वारा रद्द किया गया आदेश",
          "Order Delivered": "आदेश दिया गया",
          "Order Rejected": "आदेश अस्वीकृत",
          "Orders": "आदेश",
          "grams": "ग्राम",
          "kg": "किलोग्राम",
          "ltr": "लीटर",
          "ml": "एमएल",
          "Order Item Total": "ऑर्डर आइटम कुल",
          "Order Delivery Charge": "ऑर्डर डिलीवरी चार्ज",
          "Split Order Tax": "स्प्लिट ऑर्डर टैक्स",
          "Split Order Discount": "स्प्लिट ऑर्डर डिस्काउंट",
          "Split Order Wallet Discount": "स्प्लिट ऑर्डर वॉलेट डिस्काउंट",
          "Amount To Collect": "इकट्ठा करने के लिए राशि",
          "Deliver to": "उसे देदो",
          "Basic Detail": "मूल विवरण",
          "Order ID": "आदेश ID",
          "Payment Method": "भुगतान का तरीका",
          "COD": "सीओडी",
          "PAID": "भुगतान किया है",
          "Delivery On": "डिलीवरी चालू",
          "Order Tracking": "आदेश ट्रैकिंग",
          "User Information": "उपयोगकर्ता के लिए जानकारी",
          "Store Information": "जानकारी जमा करो",
          "Current Orders": "वर्तमान आदेश",
          "Past Orders": "पिछले आदेश",
          "Drivers": "ड्राइवरों",
          "ORDER #": "गण #",
          "Register Request": "रजिस्टर अनुरोध",
          "Verify Phone": "फ़ोन सत्यापित करें",
          "Verify E-Mail": "ईमेल सत्यापित करें",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Gender": "लिंग",
          "Male": "पुरुष",
          "Female": "मादा",
          "Status": "दर्जा",
          "Continue": "जारी रखना",
          "Your your cover image": "आपकी आपकी कवर छवि",
          "Store Address": "स्टोर का पता",
          "Choose City": "शहर चुनें",
          "Select City": "शहर चुनें",
          "Register Now": "अभी पंजीकरण करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Please enter your credentials": "कृपया अपनी साख दर्ज करें",
          "New Password": "नया पासवर्ड",
          "Update Password": "पासवर्ड अपडेट करें",
          "Received from": "से प्राप्त किया",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Account": "खाता",
          "Tracking Order": "ट्रैकिंग आदेश",
          "Order Total": "कुल आर्डर",
          "Payment Method :": "भुगतान का तरीका :",
          "Session expired!": "सत्र समाप्त हुआ!",
          "Please wait": "कृपया प्रतीक्षा करें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon": "हमें आपका अनुरोध प्राप्त हो गया है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "Okay": "ठीक",
          "Your account is blocked, please contact administrator": "आपका खाता अवरुद्ध है, कृपया व्यवस्थापक से संपर्क करें",
          "Something went wrong while signin": "साइन इन करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "Something went wrong while signup": "साइन अप करते समय कुछ गलत हुआ",
          "Phone Number is required": "फ़ोन नंबर आवश्यक है",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Verify": "सत्यापित करना",
          "Contact": "संपर्क करना",
          "Call": "बुलाना",
          "Choose status": "स्थिति चुनें",
          "Updating Order": "अद्यतन आदेश",
          "Sending OTP": "ओटीपी भेजना",
          "Location services are disabled.": "स्थान सेवाएं अक्षम हैं।",
          "Location permissions are denied": "स्थान अनुमतियां अस्वीकार कर दी गई हैं",
          "Location permissions are permanently denied, we cannot request permissions.": "स्थान अनुमतियों को स्थायी रूप से अस्वीकार कर दिया गया है, हम अनुमतियों का अनुरोध नहीं कर सकते।",
          "Contact Number Verified": "संपर्क नंबर सत्यापित",
          "Email Verified": "ईमेल सत्यापित हुआ",
          "E-mail is required": "ईमेल की जरूरत है",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Your Register Request Sent": "आपका रजिस्टर अनुरोध भेजा गया",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Start Location": "प्रारंभ स्थान",
          "End Location": "अंतिम स्थान",
          "created": "बनाया था",
          "rejected": "अस्वीकृत",
          "delivered": "पहुंचा दिया",
          "accepted": "को स्वीकृत",
          "cancelled": "रद्द",
          "ongoing": "चल रहे"
        },
        'es_DE': {
          "Profile": "Perfil",
          "Edit": "Editar",
          "Reviews": "Reseñas",
          "Change Password": "Cambia la contraseña",
          "Languages": "Idiomas",
          "Contact Us": "Contacta con nosotros",
          "Faq & Help": "Preguntas frecuentes y ayuda",
          "Privacy And Terms": "Privacidad y Términos",
          "About": "Sobre",
          "Logout": "Cerrar sesión",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "Privacy Policy": "Política de privacidad",
          "About Us": "Sobre nosotros",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Submit": "Enviar",
          "Edit Profile": "Editar perfil",
          "Choose From": "Escoge de",
          "Gallery": "Galería",
          "Camera": "Cámara",
          "Cancel": "Cancelar",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Email": "Correo electrónico",
          "Mobile No": "No móviles",
          "Available": "Disponible",
          "Save Profile": "Guardar perfil",
          "Connection Failed": "La conexión falló",
          "Could not connect to network,": "No se pudo conectar a la red,",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Verify your phone number": "verifica tu numero de telefono",
          "Fresh fruits and Vegetables": "frutas y verduras frescas",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "Las frutas y verduras frescas son una parte importante de una dieta saludable. Contienen vitaminas esenciales, minerales, fibra y otros nutrientes que son esenciales para una buena salud.",
          "Grocery to your door steps": "Comestibles a los pasos de su puerta",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "Poco a poco nos estamos volviendo más conscientes de cómo nuestras elecciones individuales pueden afectar nuestro planeta. Y la comida, cómo la consumimos y cómo la compramos, es una de las formas más importantes en que podemos marcar la diferencia.",
          "Best quality grocery": "Supermercado de la mejor calidad",
          "Best quality product with organic maintenance but with affordable price.": "Producto de la mejor calidad con mantenimiento orgánico pero con precio asequible.",
          "Fastest Delivery": "Entrega más rápida",
          "Free delivery service for highest cart value, without minimum payment.": "Servicio de entrega gratuito para el valor del carrito más alto, sin pago mínimo.",
          "Skip": "Saltar",
          "Previous": "Previo",
          "Get Started": "Empezar",
          "Next": "Próximo",
          "Welcome": "Bienvenidos",
          "Please login to your acount": "Por favor, ingrese a su cuenta",
          "Password": "Clave",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "Sign In": "Registrarse",
          "Want to delivery partner with us ?": "¿Quieres ser socio de entrega con nosotros?",
          " Join Now": " Únete ahora",
          "Phone Number": "Número de teléfono",
          "Send OTP": "Enviar OTP",
          "Order": "Ordenar",
          "Choose Status": "Elija Estado",
          "Update Status": "Estado de actualización",
          "Order Cancelled by user": "Orden cancelada por el usuario",
          "Order Delivered": "Pedido entregado",
          "Order Rejected": "Pedido rechazado",
          "Orders": "Pedidos",
          "grams": "gramos",
          "kg": "kg",
          "ltr": "litros",
          "ml": "ml",
          "Order Item Total": "Total del artículo del pedido",
          "Order Delivery Charge": "Cargo por envío del pedido",
          "Split Order Tax": "Impuesto de orden dividida",
          "Split Order Discount": "Descuento de pedido dividido",
          "Split Order Wallet Discount": "Descuento de billetera de pedido dividido",
          "Amount To Collect": "Cantidad a cobrar",
          "Deliver to": "Entregar a",
          "Basic Detail": "Detalle básico",
          "Order ID": "Solicitar ID",
          "Payment Method": "Método de pago",
          "COD": "BACALAO",
          "PAID": "PAGADO",
          "Delivery On": "Entrega en",
          "Order Tracking": "Rastreo de orden",
          "User Information": "informacion del usuario",
          "Store Information": "Almacenar información",
          "Current Orders": "Órdenes actuales",
          "Past Orders": "Pedidos anteriores",
          "Drivers": "Conductores",
          "ORDER #": "ORDENAR #",
          "Register Request": "Solicitud de registro",
          "Verify Phone": "Verificar teléfono",
          "Verify E-Mail": "Verificar correo electrónico",
          "Confirm Password": "Confirmar contraseña",
          "Gender": "Género",
          "Male": "Masculino",
          "Female": "Femenino",
          "Status": "Estado",
          "Continue": "Continuar",
          "Your your cover image": "Tu tu imagen de portada",
          "Store Address": "Store Address",
          "Choose City": "Elige Ciudad",
          "Select City": "Ciudad selecta",
          "Register Now": "Regístrate ahora",
          "Reset Password": "Restablecer la contraseña",
          "Please enter your credentials": "Por favor ingrese sus credenciales",
          "New Password": "Nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "Received from": "Recibido de",
          "No Internet Connection": "Sin conexión a Internet",
          "Account": "Cuenta",
          "Tracking Order": "Orden de seguimiento",
          "Order Total": "Total del pedido",
          "Payment Method :": "Método de pago :",
          "Session expired!": "¡Sesión expirada!",
          "Please wait": "Espere por favor",
          "All fields are required": "Todos los campos son obligatorios",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "We have received your request, we will respond on your issue soon": "Hemos recibido tu solicitud, pronto responderemos a tu problema.",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Your account is blocked, please contact administrator": "Su cuenta está bloqueada, comuníquese con el administrador",
          "Something went wrong while signin": "Algo salió mal al iniciar sesión",
          "Something went wrong": "Algo salió mal",
          "Something went wrong while signup": "Algo salió mal durante el registro",
          "Phone Number is required": "Se requiere número de teléfono",
          "Verification": "Verificación",
          "We have sent verification code on": "Hemos enviado el código de verificación el",
          "Verify": "Verificar",
          "Contact": "Contacto",
          "Call": "Llamar",
          "Choose status": "elegir estado",
          "Updating Order": "Orden de actualización",
          "Sending OTP": "Envío de OTP",
          "Location services are disabled.": "Los servicios de ubicación están deshabilitados.",
          "Location permissions are denied": "Los permisos de ubicación están denegados",
          "Location permissions are permanently denied, we cannot request permissions.": "Los permisos de ubicación se niegan permanentemente, no podemos solicitar permisos.",
          "Contact Number Verified": "Número de contacto verificado",
          "Email Verified": "Correo Electrónico Verificado",
          "E-mail is required": "Correo electronico es requerido",
          "Password mismatch": "Contraseña no coincide",
          "Your Register Request Sent": "Su solicitud de registro enviada",
          "Password Updated": "Contraseña actualiza",
          "Start Location": "Ubicación de inicio",
          "End Location": "Ubicación final",
          "created": "creado",
          "rejected": "rechazado",
          "delivered": "entregado",
          "accepted": "aceptado",
          "cancelled": "cancelado",
          "ongoing": "en curso"
        },
        'ar_AE': {
          "Profile": "الملف الشخصي",
          "Edit": "يحرر",
          "Reviews": "المراجعات",
          "Change Password": "غير كلمة السر",
          "Languages": "اللغات",
          "Contact Us": "اتصل بنا",
          "Faq & Help": "التعليمات و التعليمات",
          "Privacy And Terms": "الخصوصية والشروط",
          "About": "حول",
          "Logout": "تسجيل خروج",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Privacy Policy": "سياسة الخصوصية",
          "About Us": "معلومات عنا",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Submit": "يُقدِّم",
          "Edit Profile": "تعديل الملف الشخصي",
          "Choose From": "اختر من",
          "Gallery": "صالة عرض",
          "Camera": "آلة تصوير",
          "Cancel": "يلغي",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Email": "البريد الإلكتروني",
          "Mobile No": "رقم الموبايل",
          "Available": "متوفرة",
          "Save Profile": "احفظ الملف",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network,": "تعذر الاتصال بالشبكة ،",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى.",
          "retry": "أعد المحاولة",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "Fresh fruits and Vegetables": "فواكه وخضروات طازجة",
          "Fresh fruits and vegetables are an important part of a healthy diet. They contain essential vitamins, minerals, fiber and other nutrients that are essential for good health":
              "تعتبر الفواكه والخضروات الطازجة جزءًا مهمًا من النظام الغذائي الصحي. تحتوي على فيتامينات ومعادن وألياف أساسية وعناصر مغذية أخرى ضرورية لصحة جيدة",
          "Grocery to your door steps": "البقالة حتى عتبات بابك",
          "We're slowly becoming more aware of how our individual choices can impact our planet. And food - how we consume it and how we shop for it - is one of the most important ways we can make a difference.":
              "أصبحنا ندرك ببطء أكثر كيف يمكن لخياراتنا الفردية أن تؤثر على كوكبنا. والطعام - كيف نستهلكه وكيف نتسوق له - هو أحد أهم الطرق التي يمكننا من خلالها إحداث فرق.",
          "Best quality grocery": "أفضل بقالة جودة",
          "Best quality product with organic maintenance but with affordable price.": "أفضل منتج عالي الجودة مع صيانة عضوية ولكن بسعر مناسب.",
          "Fastest Delivery": "أسرع توصيل",
          "Free delivery service for highest cart value, without minimum payment.": "خدمة توصيل مجانية لأعلى قيمة لسلة التسوق ، بدون حد أدنى للدفع.",
          "Skip": "يتخطى",
          "Previous": "سابق",
          "Get Started": "البدء",
          "Next": "التالي",
          "Welcome": "أهلا وسهلا",
          "Please login to your acount": "يرجى تسجيل الدخول إلى حسابك",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Sign In": "تسجيل الدخول",
          "Want to delivery partner with us ?": "هل تريد شريك التسليم معنا؟",
          " Join Now": "نضم الان",
          "Phone Number": "رقم الهاتف",
          "Send OTP": "أرسل OTP",
          "Order": "ترتيب",
          "Choose Status": "اختر الحالة",
          "Update Status": "تحديث الحالة",
          "Order Cancelled by user": "تم إلغاء الطلب من قبل المستخدم",
          "Order Delivered": "أجل تسليم",
          "Order Rejected": "تم رفض الطلب",
          "Orders": "ترتيب",
          "grams": "جرامات",
          "kg": "كلغ",
          "ltr": "لتر",
          "ml": "مل",
          "Order Item Total": "إجمالي عنصر الطلب",
          "Order Delivery Charge": "رسوم توصيل الطلب",
          "Split Order Tax": "تقسيم ضريبة الطلب",
          "Split Order Discount": "خصم الطلب المقسم",
          "Split Order Wallet Discount": "خصم محفظة الطلب المقسم",
          "Amount To Collect": "المبلغ المطلوب تحصيله",
          "Deliver to": "يسلم إلى",
          "Basic Detail": "التفاصيل الأساسية",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Payment Method": "طريقة الدفع او السداد",
          "COD": "سمك القد",
          "PAID": "دفع",
          "Delivery On": "التسليم في",
          "Order Tracking": "تتبع الطلب",
          "User Information": "معلومات المستخدم",
          "Store Information": "معلومات المتجر",
          "Current Orders": "الطلبات الحالية",
          "Past Orders": "الطلبات السابقة",
          "Drivers": "السائقين",
          "ORDER #": "ترتيب #",
          "Register Request": "طلب تسجيل",
          "Verify Phone": "تحقق من الهاتف",
          "Verify E-Mail": "التحقق من البريد الإلكتروني",
          "Confirm Password": "تأكيد كلمة المرور",
          "Gender": "جنس",
          "Male": "ذكر",
          "Female": "أنثى",
          "Status": "حالة",
          "Continue": "يكمل",
          "Your your cover image": "صورة الغلاف الخاصة بك",
          "Store Address": "عنوان المتجر",
          "Choose City": "اختر المدينة",
          "Select City": "اختر مدينة",
          "Register Now": "سجل الان",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please enter your credentials": "الرجاء إدخال بيانات الاعتماد الخاصة بك",
          "New Password": "كلمة السر الجديدة",
          "Update Password": "تطوير كلمة السر",
          "Received from": "مستلم من",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Account": "الحساب",
          "Tracking Order": "طلب التتبع",
          "Order Total": "الطلب الكلي",
          "Payment Method :": "طريقة الدفع او السداد :",
          "Session expired!": "انتهت الجلسة!",
          "Please wait": "أرجو الإنتظار",
          "All fields are required": "جميع الحقول مطلوبة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "تم إرسال معلومات الاتصال",
          "Okay": "تمام",
          "Your account is blocked, please contact administrator": "تم حظر حسابك ، يرجى الاتصال بالمسؤول",
          "Something went wrong while signin": "حدث خطأ ما أثناء تسجيل الدخول",
          "Something went wrong": "هناك خطأ ما",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Contact": "اتصال",
          "Call": "مكالمة",
          "Choose status": "اختر الحالة",
          "Updating Order": "طلب التحديث",
          "Sending OTP": "إرسال OTP",
          "Location services are disabled.": "خدمات الموقع معطلة.",
          "Location permissions are denied": "تم رفض أذونات الموقع",
          "Location permissions are permanently denied, we cannot request permissions.": "أذونات الموقع مرفوضة بشكل دائم ، ولا يمكننا طلب أذونات.",
          "Contact Number Verified": "تم التحقق من رقم الاتصال",
          "Email Verified": "تم التحقق من البريد الإلكتروني",
          "E-mail is required": "البريد الالكتروني مطلوب",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Your Register Request Sent": "تم إرسال طلب التسجيل الخاص بك",
          "Password Updated": "تم تحديث كلمة السر",
          "Start Location": "بدء الموقع",
          "End Location": "موقع النهاية",
          "created": "خلقت",
          "rejected": "مرفوض",
          "delivered": "تم التوصيل",
          "accepted": "وافقت",
          "cancelled": "ألغيت",
          "ongoing": "جاري التنفيذ"
        },
      };
}
